[package]
name = "cryptoed"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.1", features = ["derive"] }
cursive = { version = "0.21.1", features = ["toml"] }
futures-util = "0.3"
tokio = { version = "1.52.3", features = ["full"] }
argon2 = "0.5.3"
chacha20poly1305 = { version = "0.11.0", features = ["alloc", "zeroize"] }
getrandom = "0.4.3"
thiserror = "2"
zeroize = "1.9"
dialoguer = "0.12.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
